spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
  redis:
    host: 124.223.77.220
    database: 0
    password: password
    port: 6379
    timeout: 20000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
logging:
  level:
    root: info
    com.dl.book: debug
